# Generated by Django 4.0.3 on 2022-04-29 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('type_of_airline', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['airline_name'],
            },
        ),
        migrations.CreateModel(
            name='PassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('ph_nbr', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['pass_id'],
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField(default=0)),
                ('seat_type', models.CharField(max_length=200)),
                ('meal_type', models.CharField(max_length=200)),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.passlist')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_name', models.CharField(max_length=200)),
                ('card_no', models.CharField(max_length=200)),
                ('sec_code', models.CharField(max_length=3)),
                ('exp_date', models.DateTimeField()),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.passlist')),
            ],
        ),
        migrations.CreateModel(
            name='FlightList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('flight_no', models.CharField(max_length=200)),
                ('seats_left', models.IntegerField(default=0)),
                ('dep_arpt', models.CharField(max_length=200)),
                ('arr_arpt', models.DateTimeField()),
                ('dep_date', models.DateTimeField()),
                ('arr_date', models.DateTimeField()),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.airline')),
            ],
            options={
                'ordering': ['flight_id'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.airline')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.flightlist')),
            ],
            options={
                'ordering': ['-emp_id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_no', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('dep_arpt', models.CharField(max_length=200)),
                ('arr_arpt', models.DateTimeField()),
                ('dep_date', models.DateTimeField()),
                ('arr_date', models.DateTimeField()),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.flightlist')),
            ],
            options={
                'ordering': ['confirmation_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='preferences',
            constraint=models.UniqueConstraint(fields=('pass_id', 'seat_no'), name='pref_id'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('pass_id', 'credit_card_name'), name='payment_id'),
        ),
    ]
