# Generated by Django 4.0.3 on 2022-03-19 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dat_pgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('type_of_airline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_pgs.airline')),
            ],
        ),
    ]
