# Generated by Django 4.0.3 on 2022-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_pgs', '0002_booking_flight_no_alter_booking_pass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arr_arpt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flightlist',
            name='arr_arpt',
            field=models.CharField(max_length=200),
        ),
    ]
