# Generated by Django 4.0.3 on 2022-03-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat_pgs', '0002_airline_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['-emp_id']},
        ),
    ]
