# Generated by Django 4.0.3 on 2022-05-01 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dat_pgs', '0003_alter_booking_arr_arpt_alter_flightlist_arr_arpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlist',
            name='flight_id',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='passlist',
            name='pass_id',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
