# Generated by Django 4.0.3 on 2022-03-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat_pgs', '0003_alter_employees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ['airline_name']},
        ),
    ]
